### ISSUE TITLE
When sending QRL, QRLNode._p2pfactory somehow not set

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/integration_tests#2]
Did not experience this a few days ago with qrl/cli.py, although I have since git pull --rebased.

```
ipdb> n
> /home/shinichi/QRL/tests_integration/qrl_testing/NodeInterface.py(50)send()
     49         f = self.stub.PushTransaction.future(pushTransactionReq, timeout=5)
---> 50         pushTransactionResp = f.result(timeout=5)
     51 

ipdb> [0092.969] node_1  | 2017-11-30 15:57:01,724|local-dev|unsynced| DEBUG : [PublicAPI] PushTransaction
All nodes in sync! Uptime: 92.9693489074707 secs
[0092.980] node_1  | 2017-11-30 15:57:01,735|local-dev|unsynced| DEBUG : Syncing wallet file
All nodes in sync! Uptime: 92.98019075393677 secs
[0092.990] node_1  | 2017-11-30 15:57:01,745|local-dev|unsynced| ERROR : Traceback (most recent call last):
******************** ******************** FAILURE TRIGGERED! ******************** ********************
All nodes in sync! Uptime: 92.99192237854004 secs
[0092.992] node_1  |   File "/home/shinichi/QRL/qrl/services/grpcHelper.py", line 20, in wrap_f
[0092.992] node_1  |     return f(caller_self, request, context)
[0092.992] node_1  |   File "/home/shinichi/QRL/qrl/services/PublicAPIService.py", line 72, in PushTransaction
[0092.992] node_1  |     submitted = self.qrlnode.submit_send_tx(tx)
[0092.992] node_1  |   File "/home/shinichi/QRL/qrl/core/qrlnode.py", line 278, in submit_send_tx
[0092.992] node_1  |     self._p2pfactory.broadcast_tx(tx)
[0092.992] node_1  | AttributeError: 'NoneType' object has no attribute 'broadcast_tx'
******************** ******************** FAILURE TRIGGERED! ******************** ********************
[0092.994] node_1  | 
******************** ******************** FAILED! ********************
```

**Comment by jleni** [comment]
This issue cannot be reproduced and seems dependent on new code being introduced
